      summary: "Leave application"
      description: "Leave add application"
      consumes:
        - multipart/form-data
      produces:
          - application/json
      parameters:
        - name: x-access-token
          in: header
          description: an authorization header
          required: true
          type: string
        - name: employee_id
          in: formData
          description: Enter employeee id .
          required: true
          type: string
        - name: span_id
          in: formData
          description: Enter span id .
          required: true
          type: string
        - name: type_id
          in: formData
          description: Enter type id .
          required: true
          type: string
        - name: description
          in: formData
          description: Enter description.
          required: true
          type: string
      tags:
        - Leave Manage
      responses:
        '200':
          description: "Successfully Leave alloted"